#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyAndroid.Resource", IsApplication=true)]

namespace MyAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int editor_item_padding_bottom = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int editor_item_padding_top = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int editor_spinner_caption_min_width = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int editor_text_size = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int image_picker_item_side = 2130968582;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int RacesDropDown = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050008
			public const int QuizStatus = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int add_question = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int edit_choice_a = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int edit_choice_b = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int edit_choice_c = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int edit_choice_d = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int edit_question = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int new_quiz = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int question_correct = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int question_incorrect = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int question_left_blank = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int question_placeholder = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int question_unanswered = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int read_from_file_button = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int reset_quiz = 2131034126;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
